// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSY7c-jQcbiZ3t1u4kdGgKK2P1TIP4iw',
    appId: '1:456914878584:web:bf09e88707a33a510aed8d',
    messagingSenderId: '456914878584',
    projectId: 'smart-park-627ed',
    authDomain: 'smart-park-627ed.firebaseapp.com',
    storageBucket: 'smart-park-627ed.firebasestorage.app',
    measurementId: 'G-KQW8J92M06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wypDw60M5XgiXhLgjInER1Ye4OxrkxI',
    appId: '1:456914878584:android:cb360bca77f92c470aed8d',
    messagingSenderId: '456914878584',
    projectId: 'smart-park-627ed',
    storageBucket: 'smart-park-627ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhStasbvlJMG70QsLhkcPctX7sdAf6ThA',
    appId: '1:456914878584:ios:2e60b2f59fd05f120aed8d',
    messagingSenderId: '456914878584',
    projectId: 'smart-park-627ed',
    storageBucket: 'smart-park-627ed.firebasestorage.app',
    androidClientId: '456914878584-69foilipijt7d64614lqp6dldmj7s8dg.apps.googleusercontent.com',
    iosClientId: '456914878584-be99b5qfscnbk1q2lmjugs7824ap21s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firsttApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhStasbvlJMG70QsLhkcPctX7sdAf6ThA',
    appId: '1:456914878584:ios:2e60b2f59fd05f120aed8d',
    messagingSenderId: '456914878584',
    projectId: 'smart-park-627ed',
    storageBucket: 'smart-park-627ed.firebasestorage.app',
    androidClientId: '456914878584-69foilipijt7d64614lqp6dldmj7s8dg.apps.googleusercontent.com',
    iosClientId: '456914878584-be99b5qfscnbk1q2lmjugs7824ap21s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firsttApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACSY7c-jQcbiZ3t1u4kdGgKK2P1TIP4iw',
    appId: '1:456914878584:web:d417a601dab4fb960aed8d',
    messagingSenderId: '456914878584',
    projectId: 'smart-park-627ed',
    authDomain: 'smart-park-627ed.firebaseapp.com',
    storageBucket: 'smart-park-627ed.firebasestorage.app',
    measurementId: 'G-XS527CKNR4',
  );
}
